export const RECV_ERROR = 'RECV_ERROR'
export const REQ_DATA = 'REQ_DATA'
export const RECV_DATA = 'RECV_DATA'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const TRIGGER_WIKI_QUERY = 'TRIGGER_WIKI_QUERY'